name: Build Maple

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Source/Meadow.Foundation.Libraries_and_Frameworks/Web.Maple/Maple.sln
    - name: Build
      run: dotnet build -c Release Source/Meadow.Foundation.Libraries_and_Frameworks/Web.Maple/Maple.sln --no-restore
    - name: Unit Tests
      run: dotnet test -c Release  Source/Meadow.Foundation.Libraries_and_Frameworks/Web.Maple/Maple.sln --no-restore --verbosity normal
    - name: Build for F7
      run: dotnet publish Source/Meadow.Foundation.Libraries_and_Frameworks/Web.Maple/Driver/Web.Maple.Server/Meadow.Foundation.Web.Maple.Server.csproj --framework netstandard2.1
    - name: Create assets
      uses: softprops/action-gh-release@v1
      with:
        files: "Maple.Server.dll"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
